markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
baseurl: /articles
exclude:
  - README.md

name: 一花一世界，一叶一菩提
host: yourdomain.com

custom:
    category:
        default: Default Category
        another: Another Category
        cpp: C++
    categories:
      - name:  default
        title: Default Category

      - name:  another
        title: Another Category

      - name: cpp
        title: C++

meta:
    author:
        name: River Lin
        email: ming.horizon@gmail.com
        disqus: whiteskyline              # Disqus缩略标识
        gcse: 012396312530956089363:hwyyhqrip50     # Google自定义搜索标识ID
        github: whiteskyline                 # GitHub账号
        gravatar: 7c1112fd29314554f3d2990380aa8858  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
